NumPy

In [ ]:
import numpy as np
import pandas as pd
print("NumPy version:",np.__version__)
print("Pandas version:",pd.__version__)

NumPy version: 2.0.2
Pandas version: 2.2.3


In [ ]:
marks=np.array([78,85,98,90,80])
print("Marks:",marks)
print("Type:",type(marks))

Marks: [78 85 98 90 80]
Type: <class 'numpy.ndarray'>


In [ ]:
print("Number of dimensions:",marks.ndim)
print("Shape:",marks.shape)
print("Number of elements:",marks.size)

Number of dimensions: 1
Shape: (5,)
Numbe of elements: 5


In [ ]:
marks=np.array([78,85,98,90,80])
print("Original:",marks)
print("Add 5:",marks+5)
print("Multiply by 2:",marks*2)
print("Divide by 2",marks/2)
print("Square:",marks**2)

Original: [78 85 98 90 80]
Add 5: [ 83  90 103  95  85]
Multiply by 2: [156 170 196 180 160]
Divide by 2 [39.  42.5 49.  45.  40. ]
Square: [6084 7225 9604 8100 6400]


In [ ]:
print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())
print("Minimum:",marks.min())


Sum: 431
Mean: 86.2
Maximum: 98
Minimum: 78


In [ ]:
print("First mark:",marks[0])
print("Second mark:",marks[1])
print("Last mark:",marks[2])

First mark: 78
Second mark: 85
Last mark: 98


In [ ]:
print("Index 1 to 3:",marks[1:4])
print("First three:",marks[:3])
print("From index 2:",marks[1:4])
print("Every second element:",marks[::2])


Index 1 to 3: [85 98 90]
First three: [78 85 98]
From index 2: [85 98 90]
Every second element: [78 98 80]


In [ ]:
student_marks=np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
])
print(student_marks)
print("Shape:",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)


In [ ]:
print("Mean of all values:",student_marks.mean())
print("Column wise mean:",student_marks.mean(axis=0))
print("Row wise mean:",student_marks.mean(axis=1))

Mean of all values: 84.44444444444444
Column wise mean: [78.33333333 89.33333333 85.66666667]
Row wise mean: [85.         77.         91.33333333]


Pandas

In [ ]:
data={
    "Name":["Anu", "Rahul","Kiran","Priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,70,80,98]
}
df=pd.DataFrame(data)
df


,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,70
2,Kiran,CSE,80
3,Priya,AIML,98


In [ ]:
print("Shape",df.shape)
print("\nColus:")
print(df.columns)

Shape (4, 3)

Colus:
Index(['Name', 'Branch', 'Marks'], dtype='object')


In [ ]:
df.head()

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,70
2,Kiran,CSE,80
3,Priya,AIML,98


In [ ]:
df.tail()

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,70
2,Kiran,CSE,80
3,Priya,AIML,98


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [ ]:
df.describe()

,Marks
count,4.000000
mean,83.250000
std,11.644026
min,70.000000
25%,77.500000
50%,82.500000
75%,88.250000
max,98.000000


selecting columns

In [ ]:
print("Marks columns:")
print((df["Marks"]))
print("\nBranch and Marks:")
print(df[["Branch","Marks"]])

Marks columns:
0    85
1    70
2    80
3    98
Name: Marks, dtype: int64

Branch and Marks:
  Branch  Marks
0    CSE     85
1   AIML     70
2    CSE     80
3   AIML     98


In [ ]:
print("First row:")
print(df.iloc[0])

print("\nSecond row:")
print(df.iloc[1])

print("\nFirst three row:")
print(df.iloc[0:3])

First row:
Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

Second row:
Name      Rahul
Branch     AIML
Marks        70
Name: 1, dtype: object

First three row:
    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     70
2  Kiran    CSE     80


In [ ]:
print("First two rows and first two columns:")
print(df.iloc[0:2, 0:2])

First two rows and first two columns:
    Name Branch
0    Anu    CSE
1  Rahul   AIML


In [ ]:
print("First three rows:")
display(df.iloc[0:3])

print("\nRows 1 to 3, Name and Marks:")
display(df.iloc[1:4,0:3])


First three rows:


,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,70
2,Kiran,CSE,80



Rows 1 to 3, Name and Marks:


,Name,Branch,Marks
1,Rahul,AIML,70
2,Kiran,CSE,80
3,Priya,AIML,98


In [ ]:
high_scores=df[df["Marks"]>=90]
high_scores

,Name,Branch,Marks
3,Priya,AIML,98


In [ ]:
print("Students from CSE:")
display(df[df["Branch"]=="CSE"])
print("\nStudents scoring 85 or above:")
display(df[df["Marks"]>=85])





Students from CSE:


,Name,Branch,Marks
0,Anu,CSE,85
2,Kiran,CSE,80



Students scoring 85 or above:


,Name,Branch,Marks
0,Anu,CSE,85
3,Priya,AIML,98


In [ ]:
data={
    "Name":["Anu", "Rahul","Kiran","Priya","Asha","Bharath"],
    "Department":["CSE","AIML","CSE","AIML","ISE","CSe"],
    "Marks":[78,89,90,98,78,84],
    "Attendance":[97,78,87,86,77,67]
}
st=pd.DataFrame(data)
st

,Name,Department,Marks,Attendance
0,Anu,CSE,78,97
1,Rahul,AIML,89,78
2,Kiran,CSE,90,87
3,Priya,AIML,98,86
4,Asha,ISE,78,77
5,Bharath,CSe,84,67


In [ ]:
print("\nName and Marks:")
print(st[["Name","Marks"]])
print("\nStudents scoring 80 or above:")
display(st[st["Marks"]>=80])


print("\nStudents having attendance above 85%:")
display(st[st["Attendance"]>=85])

print("First three rows:")
display(st.iloc[0:3])

print([st["Marks"].mean()])

print([st["Marks"].max()])

print("Students from CSE:")
display(st[st["Department"]=="CSE"])

print("\nStudents scoring 80 or above with attedance 85%:")
display(st[
        (st["Marks"]>=80) &
        (st["Attendance"]>85)]
)










Name and Marks:
      Name  Marks
0      Anu     78
1    Rahul     89
2    Kiran     90
3    Priya     98
4     Asha     78
5  Bharath     84

Students scoring 80 or above:


,Name,Department,Marks,Attendance
1,Rahul,AIML,89,78
2,Kiran,CSE,90,87
3,Priya,AIML,98,86
5,Bharath,CSe,84,67



Students having attendance above 85%:


,Name,Department,Marks,Attendance
0,Anu,CSE,78,97
2,Kiran,CSE,90,87
3,Priya,AIML,98,86


First three rows:


,Name,Department,Marks,Attendance
0,Anu,CSE,78,97
1,Rahul,AIML,89,78
2,Kiran,CSE,90,87


[np.float64(86.16666666666667)]
[98]
Students from CSE:


,Name,Department,Marks,Attendance
0,Anu,CSE,78,97
2,Kiran,CSE,90,87



Students scoring 80 or above with attedance 85%:


,Name,Department,Marks,Attendance
2,Kiran,CSE,90,87
3,Priya,AIML,98,86
